//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Serialized state of HyperLogLogPlusPlus aggregator.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: hllplus-unique.proto

package zetasketch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents an HLL++ aggregator in either sparse or normal representation.
// For more details on the algorithm, the representations and the concepts
// please check the HLL++ paper (https://goo.gl/pc916Z).
type HyperLogLogPlusUniqueStateProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Size of sparse list, i.e., how many different indexes are present in
	// "sparse_data".
	SparseSize *int32 `protobuf:"varint,2,opt,name=sparse_size,json=sparseSize" json:"sparse_size,omitempty"`
	// Precision / number of buckets for the normal representation.
	//
	// This field is used slightly differently across the v1 and v2 versions of
	// the algorithm (see the encoding_version field in the AggregatorStateProto):
	//
	//   - In v1 this field is the total number of buckets 2^p where "p" is the
	//     requested precision. Accepted values are powers of two in the [2^10,
	//     2^24] interval.
	//   - In v2 this field is the precision "p" directly. Accepted values are in
	//     the range [10, 24].
	//
	// Encoding the precision rather than the number of buckets allows us to save
	// 1-2 bytes which makes a fair difference when storing many small
	// cardinalities.
	//
	// Note that different implementations might choose to not support the whole
	// range of precisions from [10, 24].
	PrecisionOrNumBuckets *int32 `protobuf:"varint,3,opt,name=precision_or_num_buckets,json=precisionOrNumBuckets" json:"precision_or_num_buckets,omitempty"`
	// Precision / number of buckets for sparse representation.
	//
	// This field is used slightly differently across the v1 and v2 versions of
	// the algorithm (see the encoding_version field in the AggregatorStateProto):
	//
	//   - In v1 this field is 2^sp where "sp" is the sparse precision. Accepted
	//     values are powers of two in the [2^p, 2^25] interval.
	//   - In v2 this field represents the precision "sp" directly. Accepted
	//     values are in the range [p, 25].
	//
	// Encoding the precision rather than the number of buckets allows us to save
	// 2-3 bytes which makes a fair difference when storing many small
	// cardinalities.
	SparsePrecisionOrNumBuckets *int32 `protobuf:"varint,4,opt,name=sparse_precision_or_num_buckets,json=sparsePrecisionOrNumBuckets" json:"sparse_precision_or_num_buckets,omitempty"`
	// Normal data representation. If this field is populated, there are exactly
	// 2^p bytes in it.
	//
	// data[idx] represents rhoW for the substream with the given "idx". See the
	// the HLL++ paper (https://goo.gl/pc916Z) for a description of how "rhoW" and
	// "idx" are computed.
	Data []byte `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
	// Sparse data representation.
	//
	// IMPORTANT: It is considered an error if the size of this field is bigger
	// than precision_or_num_buckets (v1), resp. 2^precision_or_num_buckets (v2).
	// The normal encoding should be used in this case since the memory usage
	// would be smaller.
	//
	// For a sorted list of unsigned integers representing sparse data encodings,
	// this field contains the varint encoding for the differences between
	// consecutive values in the list:
	//
	//	list[0], list[1] - list[0], ... , list[n] - list[n - 1]
	//
	// Note: if "encoding_version" of the enclosing AggregatorStateProto is 1, the
	// diffs are encoded as signed varints using ZigZag encoding and the
	// sparse encodings are the ones defined in the HLL++ paper
	// (https://goo.gl/pc916Z), i.e., different than the ones below.
	//
	// In v2, there are two encodings possible for a value in sparse data format:
	// enc(idx, rhoW) = 1) 1 << (max(sp, p+6)) | (idx >> (sp - p)) | rhoW
	//
	//	  if the last sp - p bits of idx are all 0;
	//	2) idx, otherwise.
	SparseData    []byte `protobuf:"bytes,6,opt,name=sparse_data,json=sparseData" json:"sparse_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HyperLogLogPlusUniqueStateProto) Reset() {
	*x = HyperLogLogPlusUniqueStateProto{}
	mi := &file_hllplus_unique_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HyperLogLogPlusUniqueStateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HyperLogLogPlusUniqueStateProto) ProtoMessage() {}

func (x *HyperLogLogPlusUniqueStateProto) ProtoReflect() protoreflect.Message {
	mi := &file_hllplus_unique_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HyperLogLogPlusUniqueStateProto.ProtoReflect.Descriptor instead.
func (*HyperLogLogPlusUniqueStateProto) Descriptor() ([]byte, []int) {
	return file_hllplus_unique_proto_rawDescGZIP(), []int{0}
}

func (x *HyperLogLogPlusUniqueStateProto) GetSparseSize() int32 {
	if x != nil && x.SparseSize != nil {
		return *x.SparseSize
	}
	return 0
}

func (x *HyperLogLogPlusUniqueStateProto) GetPrecisionOrNumBuckets() int32 {
	if x != nil && x.PrecisionOrNumBuckets != nil {
		return *x.PrecisionOrNumBuckets
	}
	return 0
}

func (x *HyperLogLogPlusUniqueStateProto) GetSparsePrecisionOrNumBuckets() int32 {
	if x != nil && x.SparsePrecisionOrNumBuckets != nil {
		return *x.SparsePrecisionOrNumBuckets
	}
	return 0
}

func (x *HyperLogLogPlusUniqueStateProto) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HyperLogLogPlusUniqueStateProto) GetSparseData() []byte {
	if x != nil {
		return x.SparseData
	}
	return nil
}

var file_hllplus_unique_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*AggregatorStatsProto)(nil),
		ExtensionType: (*UniqueStatsProto)(nil),
		Field:         112,
		Name:          "zetasketch.hyperloglog_plus_unique_stats",
		Tag:           "bytes,112,opt,name=hyperloglog_plus_unique_stats",
		Filename:      "hllplus-unique.proto",
	},
	{
		ExtendedType:  (*AggregatorStateProto)(nil),
		ExtensionType: (*HyperLogLogPlusUniqueStateProto)(nil),
		Field:         112,
		Name:          "zetasketch.hyperloglogplus_unique_state",
		Tag:           "bytes,112,opt,name=hyperloglogplus_unique_state",
		Filename:      "hllplus-unique.proto",
	},
}

// Extension fields to AggregatorStatsProto.
var (
	// This field id should match AggregatorType.HYPERLOGLOG_PLUS_UNIQUE
	//
	// optional zetasketch.UniqueStatsProto hyperloglog_plus_unique_stats = 112;
	E_HyperloglogPlusUniqueStats = &file_hllplus_unique_proto_extTypes[0]
)

// Extension fields to AggregatorStateProto.
var (
	// This field id should match AggregatorType.HYPERLOGLOG_PLUS_UNIQUE
	//
	// optional zetasketch.HyperLogLogPlusUniqueStateProto hyperloglogplus_unique_state = 112;
	E_HyperloglogplusUniqueState = &file_hllplus_unique_proto_extTypes[1]
)

var File_hllplus_unique_proto protoreflect.FileDescriptor

const file_hllplus_unique_proto_rawDesc = "" +
	"\n" +
	"\x14hllplus-unique.proto\x12\n" +
	"zetasketch\x1a\x10aggregator.proto\x1a\x12unique-stats.proto\"\x8a\x02\n" +
	"\x1fHyperLogLogPlusUniqueStateProto\x12\x1f\n" +
	"\vsparse_size\x18\x02 \x01(\x05R\n" +
	"sparseSize\x127\n" +
	"\x18precision_or_num_buckets\x18\x03 \x01(\x05R\x15precisionOrNumBuckets\x12D\n" +
	"\x1fsparse_precision_or_num_buckets\x18\x04 \x01(\x05R\x1bsparsePrecisionOrNumBuckets\x12\x16\n" +
	"\x04data\x18\x05 \x01(\fB\x02\b\x01R\x04data\x12#\n" +
	"\vsparse_data\x18\x06 \x01(\fB\x02\b\x01R\n" +
	"sparseDataJ\x04\b\x01\x10\x02J\x04\b\a\x10\b:\x81\x01\n" +
	"\x1dhyperloglog_plus_unique_stats\x12 .zetasketch.AggregatorStatsProto\x18p \x01(\v2\x1c.zetasketch.UniqueStatsProtoR\x1ahyperloglogPlusUniqueStats:\x8f\x01\n" +
	"\x1chyperloglogplus_unique_state\x12 .zetasketch.AggregatorStateProto\x18p \x01(\v2+.zetasketch.HyperLogLogPlusUniqueStateProtoR\x1ahyperloglogplusUniqueStateB\x1e\n" +
	"\x1ccom.google.protos.zetasketch"

var (
	file_hllplus_unique_proto_rawDescOnce sync.Once
	file_hllplus_unique_proto_rawDescData []byte
)

func file_hllplus_unique_proto_rawDescGZIP() []byte {
	file_hllplus_unique_proto_rawDescOnce.Do(func() {
		file_hllplus_unique_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hllplus_unique_proto_rawDesc), len(file_hllplus_unique_proto_rawDesc)))
	})
	return file_hllplus_unique_proto_rawDescData
}

var file_hllplus_unique_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hllplus_unique_proto_goTypes = []any{
	(*HyperLogLogPlusUniqueStateProto)(nil), // 0: zetasketch.HyperLogLogPlusUniqueStateProto
	(*AggregatorStatsProto)(nil),            // 1: zetasketch.AggregatorStatsProto
	(*AggregatorStateProto)(nil),            // 2: zetasketch.AggregatorStateProto
	(*UniqueStatsProto)(nil),                // 3: zetasketch.UniqueStatsProto
}
var file_hllplus_unique_proto_depIdxs = []int32{
	1, // 0: zetasketch.hyperloglog_plus_unique_stats:extendee -> zetasketch.AggregatorStatsProto
	2, // 1: zetasketch.hyperloglogplus_unique_state:extendee -> zetasketch.AggregatorStateProto
	3, // 2: zetasketch.hyperloglog_plus_unique_stats:type_name -> zetasketch.UniqueStatsProto
	0, // 3: zetasketch.hyperloglogplus_unique_state:type_name -> zetasketch.HyperLogLogPlusUniqueStateProto
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hllplus_unique_proto_init() }
func file_hllplus_unique_proto_init() {
	if File_hllplus_unique_proto != nil {
		return
	}
	file_aggregator_proto_init()
	file_unique_stats_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hllplus_unique_proto_rawDesc), len(file_hllplus_unique_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_hllplus_unique_proto_goTypes,
		DependencyIndexes: file_hllplus_unique_proto_depIdxs,
		MessageInfos:      file_hllplus_unique_proto_msgTypes,
		ExtensionInfos:    file_hllplus_unique_proto_extTypes,
	}.Build()
	File_hllplus_unique_proto = out.File
	file_hllplus_unique_proto_goTypes = nil
	file_hllplus_unique_proto_depIdxs = nil
}
