//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Common message for cardinality estimation stats.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.11.3
// source: zetasketch/unique-stats.proto

package zetasketch

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type UniqueStatsProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The estimated number of unique elements in the input set.
	EstimatedCardinality *int64 `protobuf:"varint,1,opt,name=estimated_cardinality,json=estimatedCardinality" json:"estimated_cardinality,omitempty"`
	// The expected error of the estimation algorithm.
	ExpectedError *float64 `protobuf:"fixed64,2,opt,name=expected_error,json=expectedError" json:"expected_error,omitempty"`
}

func (x *UniqueStatsProto) Reset() {
	*x = UniqueStatsProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zetasketch_unique_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UniqueStatsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueStatsProto) ProtoMessage() {}

func (x *UniqueStatsProto) ProtoReflect() protoreflect.Message {
	mi := &file_zetasketch_unique_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueStatsProto.ProtoReflect.Descriptor instead.
func (*UniqueStatsProto) Descriptor() ([]byte, []int) {
	return file_zetasketch_unique_stats_proto_rawDescGZIP(), []int{0}
}

func (x *UniqueStatsProto) GetEstimatedCardinality() int64 {
	if x != nil && x.EstimatedCardinality != nil {
		return *x.EstimatedCardinality
	}
	return 0
}

func (x *UniqueStatsProto) GetExpectedError() float64 {
	if x != nil && x.ExpectedError != nil {
		return *x.ExpectedError
	}
	return 0
}

var File_zetasketch_unique_stats_proto protoreflect.FileDescriptor

var file_zetasketch_unique_stats_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x7a, 0x65, 0x74, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x2f, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x2d, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x7a, 0x65, 0x74, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68, 0x22, 0x6e, 0x0a, 0x10, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x33, 0x0a, 0x15, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x61, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14,
	0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x43, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x6c, 0x69, 0x74, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x65, 0x78,
	0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x1e, 0x0a, 0x1c, 0x63,
	0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x7a, 0x65, 0x74, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x63, 0x68,
}

var (
	file_zetasketch_unique_stats_proto_rawDescOnce sync.Once
	file_zetasketch_unique_stats_proto_rawDescData = file_zetasketch_unique_stats_proto_rawDesc
)

func file_zetasketch_unique_stats_proto_rawDescGZIP() []byte {
	file_zetasketch_unique_stats_proto_rawDescOnce.Do(func() {
		file_zetasketch_unique_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_zetasketch_unique_stats_proto_rawDescData)
	})
	return file_zetasketch_unique_stats_proto_rawDescData
}

var file_zetasketch_unique_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_zetasketch_unique_stats_proto_goTypes = []interface{}{
	(*UniqueStatsProto)(nil), // 0: zetasketch.UniqueStatsProto
}
var file_zetasketch_unique_stats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zetasketch_unique_stats_proto_init() }
func file_zetasketch_unique_stats_proto_init() {
	if File_zetasketch_unique_stats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zetasketch_unique_stats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UniqueStatsProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zetasketch_unique_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zetasketch_unique_stats_proto_goTypes,
		DependencyIndexes: file_zetasketch_unique_stats_proto_depIdxs,
		MessageInfos:      file_zetasketch_unique_stats_proto_msgTypes,
	}.Build()
	File_zetasketch_unique_stats_proto = out.File
	file_zetasketch_unique_stats_proto_rawDesc = nil
	file_zetasketch_unique_stats_proto_goTypes = nil
	file_zetasketch_unique_stats_proto_depIdxs = nil
}
