//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Common message for cardinality estimation stats.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: unique-stats.proto

package zetasketch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UniqueStatsProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The estimated number of unique elements in the input set.
	EstimatedCardinality *int64 `protobuf:"varint,1,opt,name=estimated_cardinality,json=estimatedCardinality" json:"estimated_cardinality,omitempty"`
	// The expected error of the estimation algorithm.
	ExpectedError *float64 `protobuf:"fixed64,2,opt,name=expected_error,json=expectedError" json:"expected_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueStatsProto) Reset() {
	*x = UniqueStatsProto{}
	mi := &file_unique_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueStatsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueStatsProto) ProtoMessage() {}

func (x *UniqueStatsProto) ProtoReflect() protoreflect.Message {
	mi := &file_unique_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueStatsProto.ProtoReflect.Descriptor instead.
func (*UniqueStatsProto) Descriptor() ([]byte, []int) {
	return file_unique_stats_proto_rawDescGZIP(), []int{0}
}

func (x *UniqueStatsProto) GetEstimatedCardinality() int64 {
	if x != nil && x.EstimatedCardinality != nil {
		return *x.EstimatedCardinality
	}
	return 0
}

func (x *UniqueStatsProto) GetExpectedError() float64 {
	if x != nil && x.ExpectedError != nil {
		return *x.ExpectedError
	}
	return 0
}

var File_unique_stats_proto protoreflect.FileDescriptor

const file_unique_stats_proto_rawDesc = "" +
	"\n" +
	"\x12unique-stats.proto\x12\n" +
	"zetasketch\"n\n" +
	"\x10UniqueStatsProto\x123\n" +
	"\x15estimated_cardinality\x18\x01 \x01(\x03R\x14estimatedCardinality\x12%\n" +
	"\x0eexpected_error\x18\x02 \x01(\x01R\rexpectedErrorB\x1e\n" +
	"\x1ccom.google.protos.zetasketch"

var (
	file_unique_stats_proto_rawDescOnce sync.Once
	file_unique_stats_proto_rawDescData []byte
)

func file_unique_stats_proto_rawDescGZIP() []byte {
	file_unique_stats_proto_rawDescOnce.Do(func() {
		file_unique_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_unique_stats_proto_rawDesc), len(file_unique_stats_proto_rawDesc)))
	})
	return file_unique_stats_proto_rawDescData
}

var file_unique_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_unique_stats_proto_goTypes = []any{
	(*UniqueStatsProto)(nil), // 0: zetasketch.UniqueStatsProto
}
var file_unique_stats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_unique_stats_proto_init() }
func file_unique_stats_proto_init() {
	if File_unique_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_unique_stats_proto_rawDesc), len(file_unique_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unique_stats_proto_goTypes,
		DependencyIndexes: file_unique_stats_proto_depIdxs,
		MessageInfos:      file_unique_stats_proto_msgTypes,
	}.Build()
	File_unique_stats_proto = out.File
	file_unique_stats_proto_goTypes = nil
	file_unique_stats_proto_depIdxs = nil
}
